### DATA CLEANING & ENGINGEERING

#### Import Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns; sns.set()

%matplotlib inline

#### Read & Store Data

In [2]:
df = pd.read_pickle("Diabetes_2018.pkl") # Read Picklet file

#### Copy Data

In [3]:
df_clean = df.copy()

#### Select Relevant Features

In [4]:
selectFeatures = ['EXERANY2', 'SLEPTIM1', 'CVDINFR4', 'CVDCRHD4', 'CVDSTRK3', 'ASTHMA3', 'ASTHNOW', 'CHCSCNCR', 
                  'CHCOCNCR', 'CHCCOPD1', 'HAVARTH3', 'ADDEPEV2', 'CHCKDNY1', 'SEX1', 'WEIGHT2', 'HEIGHT3', 
                  'PREGNANT', 'HADHYST2', 'COPDCOGH', 'COPDFLEM', 'COPDBRTH', 'CNCRAGE', 'CNCRTYP1','CSRVTRT2', 
                  '_IMPRACE', '_AGEG5YR', 'DIABETE3']

for data in [df_clean]:
    df_clean = data.loc[:, selectFeatures]

In [5]:
df.names       = 'Diabetes Full Dataset'
df_clean.names = 'Diabetes Cleaned Dataset'

#### Display Top 5 Rows

In [6]:
df_clean.head(5)

,EXERANY2,SLEPTIM1,CVDINFR4,CVDCRHD4,CVDSTRK3,ASTHMA3,ASTHNOW,CHCSCNCR,CHCOCNCR,CHCCOPD1,...,HADHYST2,COPDCOGH,COPDFLEM,COPDBRTH,CNCRAGE,CNCRTYP1,CSRVTRT2,_IMPRACE,_AGEG5YR,DIABETE3
0,2.0,7.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0,2.0,...,1.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0,13.0,3.0
1,1.0,5.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,...,2.0,2.0,2.0,2.0,NaN,NaN,NaN,2.0,3.0,3.0
2,1.0,7.0,2.0,2.0,1.0,2.0,NaN,2.0,2.0,2.0,...,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0,12.0,1.0
3,1.0,6.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,...,NaN,2.0,2.0,2.0,NaN,NaN,NaN,1.0,10.0,3.0
4,2.0,7.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,...,1.0,2.0,2.0,2.0,NaN,NaN,NaN,1.0,5.0,3.0

#### Check Info

In [7]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 437436 entries, 0 to 437435
Data columns (total 27 columns):
EXERANY2    437411 non-null float64
SLEPTIM1    437413 non-null float64
CVDINFR4    437413 non-null float64
CVDCRHD4    437413 non-null float64
CVDSTRK3    437413 non-null float64
ASTHMA3     437413 non-null float64
ASTHNOW     61816 non-null float64
CHCSCNCR    437413 non-null float64
CHCOCNCR    437413 non-null float64
CHCCOPD1    437413 non-null float64
HAVARTH3    437411 non-null float64
ADDEPEV2    437412 non-null float64
CHCKDNY1    437412 non-null float64
SEX1        437436 non-null float64
WEIGHT2     430989 non-null float64
HEIGHT3     430238 non-null float64
PREGNANT    78410 non-null float64
HADHYST2    223694 non-null float64
COPDCOGH    81032 non-null float64
COPDFLEM    81668 non-null float64
COPDBRTH    81609 non-null float64
CNCRAGE     6191 non-null float64
CNCRTYP1    6187 non-null float64
CSRVTRT2    6184 non-null float64
_IMPRACE    437436 non-null float64
_AGEG5YR    437436 non-null float64
DIABETE3    437412 non-null float64
dtypes: float64(27)
memory usage: 90.1 MB

#### Check Shape

In [8]:
df_clean.shape

(437436, 27)

#### Check Missing Values per Column

In [9]:
for data in [df_clean]:
    print("{} Features with Null Values:\n\n {}\n".format(data.names, data.isnull().sum()))

Diabetes Cleaned Dataset Features with Null Values:

 EXERANY2        25
SLEPTIM1        23
CVDINFR4        23
CVDCRHD4        23
CVDSTRK3        23
ASTHMA3         23
ASTHNOW     375620
CHCSCNCR        23
CHCOCNCR        23
CHCCOPD1        23
HAVARTH3        25
ADDEPEV2        24
CHCKDNY1        24
SEX1             0
WEIGHT2       6447
HEIGHT3       7198
PREGNANT    359026
HADHYST2    213742
COPDCOGH    356404
COPDFLEM    355768
COPDBRTH    355827
CNCRAGE     431245
CNCRTYP1    431249
CSRVTRT2    431252
_IMPRACE         0
_AGEG5YR         0
DIABETE3        24
dtype: int64

#### Check Unique Values per Column

In [10]:
# Find the number, names and count of unique values for each column
for x in df_clean.columns.tolist():
    print("Analysis for column: ", x.upper(), "\n")
    print("Number of Unique values for the given column: ", len(df_clean[x].unique()), "\n")
    print("Unique Values: \n", df_clean[x].unique(), "\n")
    values_counts = sorted(dict(df_clean[x].value_counts()).items(), key=lambda x: x[0])
    for key, val in values_counts:
        if val > 1:
            print('Frequency of value:\t {} \t=> \t {}'.format(key, val))
    print("\nxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n")

Analysis for column:  EXERANY2

Number of Unique values for the given column:  5

Unique Values:
 [ 2.  1.  7. nan  9.]

Frequency of value:	 1.0 	=> 	 326472
Frequency of value:	 2.0 	=> 	 110269
Frequency of value:	 7.0 	=> 	 482
Frequency of value:	 9.0 	=> 	 188

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  SLEPTIM1

Number of Unique values for the given column:  27

Unique Values:
 [ 7.  5.  6.  8. 10.  4.  9. 12. 77. 14.  2.  3. 18. 15. 99. 11. 13.  1.
 20. 16. nan 24. 17. 21. 23. 22. 19.]

Frequency of value:	 1.0 	=> 	 881
Frequency of value:	 2.0 	=> 	 1403
Frequency of value:	 3.0 	=> 	 3239
Frequency of value:	 4.0 	=> 	 12696
Frequency of value:	 5.0 	=> 	 29241
Frequency of value:	 6.0 	=> 	 94849
Frequency of value:	 7.0 	=> 	 128272
Frequency of value:	 8.0 	=> 	 126353
Frequency of value:	 9.0 	=> 	 19241
Frequency of value:	 10.0 	=> 	 10282
Frequency of value:	 11.0 	=> 	 653
Frequency of value:	 12.0 	=> 	 3292
Frequency of value:	 13.0 	=> 	 169
Frequency of value:	 14.0 	=> 	 374
Frequency of value:	 15.0 	=> 	 330
Frequency of value:	 16.0 	=> 	 358
Frequency of value:	 17.0 	=> 	 38
Frequency of value:	 18.0 	=> 	 176
Frequency of value:	 19.0 	=> 	 6
Frequency of value:	 20.0 	=> 	 139
Frequency of value:	 21.0 	=> 	 10
Frequency of value:	 22.0 	=> 	 16
Frequency of value:	 23.0 	=> 	 16
Frequency of value:	 24.0 	=> 	 65
Frequency of value:	 77.0 	=> 	 4838
Frequency of value:	 99.0 	=> 	 476

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  CVDINFR4

Number of Unique values for the given column:  5

Unique Values:
 [ 2.  1.  7.  9. nan]

Frequency of value:	 1.0 	=> 	 26412
Frequency of value:	 2.0 	=> 	 408706
Frequency of value:	 7.0 	=> 	 2055
Frequency of value:	 9.0 	=> 	 240

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  CVDCRHD4

Number of Unique values for the given column:  5

Unique Values:
 [ 2.  1.  7.  9. nan]

Frequency of value:	 1.0 	=> 	 26114
Frequency of value:	 2.0 	=> 	 407649
Frequency of value:	 7.0 	=> 	 3379
Frequency of value:	 9.0 	=> 	 271

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  CVDSTRK3

Number of Unique values for the given column:  5

Unique Values:
 [ 2.  1.  7.  9. nan]

Frequency of value:	 1.0 	=> 	 18999
Frequency of value:	 2.0 	=> 	 417086
Frequency of value:	 7.0 	=> 	 1108
Frequency of value:	 9.0 	=> 	 220

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  ASTHMA3

Number of Unique values for the given column:  5

Unique Values:
 [ 2.  1.  7.  9. nan]

Frequency of value:	 1.0 	=> 	 61816
Frequency of value:	 2.0 	=> 	 374205
Frequency of value:	 7.0 	=> 	 1176
Frequency of value:	 9.0 	=> 	 216

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  ASTHNOW

Number of Unique values for the given column:  5

Unique Values:
 [nan  1.  2.  7.  9.]

Frequency of value:	 1.0 	=> 	 41974
Frequency of value:	 2.0 	=> 	 17959
Frequency of value:	 7.0 	=> 	 1854
Frequency of value:	 9.0 	=> 	 29

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  CHCSCNCR

Number of Unique values for the given column:  5

Unique Values:
 [ 1.  2.  7.  9. nan]

Frequency of value:	 1.0 	=> 	 40746
Frequency of value:	 2.0 	=> 	 395363
Frequency of value:	 7.0 	=> 	 1084
Frequency of value:	 9.0 	=> 	 220

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  CHCOCNCR

Number of Unique values for the given column:  5

Unique Values:
 [ 2.  1.  7.  9. nan]

Frequency of value:	 1.0 	=> 	 42903
Frequency of value:	 2.0 	=> 	 393295
Frequency of value:	 7.0 	=> 	 925
Frequency of value:	 9.0 	=> 	 290

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  CHCCOPD1

Number of Unique values for the given column:  5

Unique Values:
 [ 2.  1.  7.  9. nan]

Frequency of value:	 1.0 	=> 	 37337
Frequency of value:	 2.0 	=> 	 397898
Frequency of value:	 7.0 	=> 	 1935
Frequency of value:	 9.0 	=> 	 243

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  HAVARTH3

Number of Unique values for the given column:  5

Unique Values:
 [ 1.  2.  9.  7. nan]

Frequency of value:	 1.0 	=> 	 149614
Frequency of value:	 2.0 	=> 	 285288
Frequency of value:	 7.0 	=> 	 2231
Frequency of value:	 9.0 	=> 	 278

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  ADDEPEV2

Number of Unique values for the given column:  5

Unique Values:
 [ 2.  1.  7.  9. nan]

Frequency of value:	 1.0 	=> 	 81809
Frequency of value:	 2.0 	=> 	 353474
Frequency of value:	 7.0 	=> 	 1646
Frequency of value:	 9.0 	=> 	 483

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  CHCKDNY1

Number of Unique values for the given column:  5

Unique Values:
 [ 2.  1.  7.  9. nan]

Frequency of value:	 1.0 	=> 	 16647
Frequency of value:	 2.0 	=> 	 419103
Frequency of value:	 7.0 	=> 	 1420
Frequency of value:	 9.0 	=> 	 242

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  SEX1

Number of Unique values for the given column:  4

Unique Values:
 [2. 1. 9. 7.]

Frequency of value:	 1.0 	=> 	 197412
Frequency of value:	 2.0 	=> 	 238911
Frequency of value:	 7.0 	=> 	 431
Frequency of value:	 9.0 	=> 	 682

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  WEIGHT2

Number of Unique values for the given column:  568

Unique Values:
 [ 130.  200.  142.  190. 7777.  172.  150.  205.  151.  199.  170.  160.
  285.  217.  230.  250.  155.  138.  240.  185.  165.  131.  119.  180.
  169.  128.  218.  148.  147.  146.  288.  134.  152.  144.  299.  247.
  167.  275.  177.  300.  125.  175.  135. 9999.  166.  158.  232.  222.
  210.  237.  188.  225.  120.  228.  235.  182.  220.  127.  145.  198.
  215.  159.  168.   82.  153.  140.  226.  238.  195.  207.  204.  224.
  270.  212.   95.  245.  105.  102.  214.  118.  243.  116.  206.  233.
  164.  280.  123.  112.  253.   86.  156.  187.  203.  202.  110.  162.
  136.  149.  100.  154.  290.   85.  141.  260.  239.  229.  255.  163.
  227.  173.  126.  330.  192.  196.  351.  115.  132.  124.  335.   nan
   84.  178.  269.  310.  107.  113.  104.  201.  183.  211.  325.  114.
  191.  179.  184.  248.  181.  117.  121.  193.  139.  258.  189.  174.
  157.  129.  254.  265.  322.  143.  137.  417.  133.  252.  194.  208.
  213.  278.   97.  320.  274.  122.  380.  242.  223.  323.  111.  302.
  295.  264.  186.  340.  236.   98.  283.  171.  273.  109.  197.  257.
  176.   96.  161.  209.  268.  221.  281.  231.   89.  216.  244.  370.
  500.  279.  262.   83.   99.   90.  315.   88.  219.   93.   92.  303.
  297.  287.  272.  261.  256.  101.  234.  271. 9070.  282.   80.  286.
  296.  347.  400.  305.  291.  318.  106.  336.  434.  312.  690.  241.
  259.  263.  251.  350.  410.  328.  326.  249.  425.  108.  289.  371.
  284.  246.  360.  624.  385. 9055.  388.  480.  306.   60.  277.  334.
   74.  381.  458.  103.  267.  505.  450.  440.  483.  342.  365.  276.
   51.   94. 9067.  341.  266. 9112.  308.  327.  298.  332.  395. 9089.
  430. 9120.  309.   87. 9065.  292. 9071. 9073. 9050. 9090. 9058. 9076.
 9085. 9080.  375.  345. 9077. 9108. 9078. 9040. 9072.  369.  319.  294.
  349. 9088. 9074.  576. 9099.   91. 9066.  354. 9081. 9075.   50.  485.
 9054.  453.  362.  390.  456.   75.  301.  324.  359.  304.  293.  317.
  348. 9052.  313.  465.   58.   70. 9095. 9060. 9082.   76.  439. 9056.
  383. 9092.  393.  314.  435.   57.  415.  364.  508.   67.  372.  307.
  402.   71.  511.  355.  311. 9115.  455.  338. 9084. 9051. 9100.  420.
  373. 9064. 9102. 9061.   68.  530.  329. 9094.  600.   63. 9053. 9045.
 9035.  344. 9083.  399.   81. 9096.  404. 9097. 9036. 9062.  353. 9104.
  398.  460. 9068. 9063.  419.  352.  333. 9048.  382.  403.  510. 9079.
  416.  366.   78.  368.  411.  470.  389.  418.  550.  339.  394. 9059.
  356. 9277. 9086. 9210. 9087.  517.   73.  321.  386.  343. 9057.  595.
 9105. 9069. 9130. 9170.  374. 9046.  337.  358.  468.  486. 9185.  570.
  498.  520. 9049. 9093.   79.  316.  494.   65.  401.  445. 9103.  464.
  346.  452.  426. 9190.  376.  525. 9042.  712. 9041.  378.  391.  424.
  635.  462.  436.   77.  412.  423.  379.  437. 9110.  514.  407.  777.
  427. 9129.   64.   72.  507.  357.  501. 9109.  448.  545. 9111.  632.
 9157. 9117. 1358.  392. 9106.  331.  384. 9107.  469. 9034.  490. 9030.
 9124. 9200.  776.  443.  560.  405.  422.  408.  444. 9091.  406. 9113.
  409.  387. 9098.  363. 9225.  467. 9025.   56. 9150. 9155.  421. 9352.
  601.  447.  575. 9024.  648.  610.   69. 9043.  555.  475.  504.  509.
 9175.   66.  714. 9125.  361.  367.  580.  540.  479.  431. 9156.  397.
   52. 9158. 9047.  442. 9140.  377.  590.  999. 9220.  512.  503. 9132.
   55.  472. 9101.  429. 9145. 9230. 9250.   62.  663. 9164. 9180. 9165.
 9142. 9128.  722.  473.]

Frequency of value:	 50.0 	=> 	 28
Frequency of value:	 52.0 	=> 	 3
Frequency of value:	 55.0 	=> 	 3
Frequency of value:	 57.0 	=> 	 2
Frequency of value:	 58.0 	=> 	 2
Frequency of value:	 60.0 	=> 	 18
Frequency of value:	 62.0 	=> 	 2
Frequency of value:	 63.0 	=> 	 3
Frequency of value:	 65.0 	=> 	 7
Frequency of value:	 66.0 	=> 	 3
Frequency of value:	 68.0 	=> 	 3
Frequency of value:	 70.0 	=> 	 24
Frequency of value:	 71.0 	=> 	 2
Frequency of value:	 72.0 	=> 	 7
Frequency of value:	 73.0 	=> 	 7
Frequency of value:	 74.0 	=> 	 5
Frequency of value:	 75.0 	=> 	 22
Frequency of value:	 76.0 	=> 	 12
Frequency of value:	 77.0 	=> 	 7
Frequency of value:	 78.0 	=> 	 12
Frequency of value:	 79.0 	=> 	 6
Frequency of value:	 80.0 	=> 	 83
Frequency of value:	 81.0 	=> 	 14
Frequency of value:	 82.0 	=> 	 29
Frequency of value:	 83.0 	=> 	 22
Frequency of value:	 84.0 	=> 	 25
Frequency of value:	 85.0 	=> 	 103
Frequency of value:	 86.0 	=> 	 41
Frequency of value:	 87.0 	=> 	 44
Frequency of value:	 88.0 	=> 	 51
Frequency of value:	 89.0 	=> 	 66
Frequency of value:	 90.0 	=> 	 262
Frequency of value:	 91.0 	=> 	 42
Frequency of value:	 92.0 	=> 	 107
Frequency of value:	 93.0 	=> 	 84
Frequency of value:	 94.0 	=> 	 107
Frequency of value:	 95.0 	=> 	 378
Frequency of value:	 96.0 	=> 	 126
Frequency of value:	 97.0 	=> 	 137
Frequency of value:	 98.0 	=> 	 338
Frequency of value:	 99.0 	=> 	 138
Frequency of value:	 100.0 	=> 	 1352
Frequency of value:	 101.0 	=> 	 135
Frequency of value:	 102.0 	=> 	 332
Frequency of value:	 103.0 	=> 	 350
Frequency of value:	 104.0 	=> 	 331
Frequency of value:	 105.0 	=> 	 1354
Frequency of value:	 106.0 	=> 	 352
Frequency of value:	 107.0 	=> 	 400
Frequency of value:	 108.0 	=> 	 581
Frequency of value:	 109.0 	=> 	 280
Frequency of value:	 110.0 	=> 	 3056
Frequency of value:	 111.0 	=> 	 218
Frequency of value:	 112.0 	=> 	 957
Frequency of value:	 113.0 	=> 	 530
Frequency of value:	 114.0 	=> 	 636
Frequency of value:	 115.0 	=> 	 3332
Frequency of value:	 116.0 	=> 	 625
Frequency of value:	 117.0 	=> 	 683
Frequency of value:	 118.0 	=> 	 1367
Frequency of value:	 119.0 	=> 	 448
Frequency of value:	 120.0 	=> 	 6633
Frequency of value:	 121.0 	=> 	 370
Frequency of value:	 122.0 	=> 	 1045
Frequency of value:	 123.0 	=> 	 909
Frequency of value:	 124.0 	=> 	 934
Frequency of value:	 125.0 	=> 	 6192
Frequency of value:	 126.0 	=> 	 925
Frequency of value:	 127.0 	=> 	 1181
Frequency of value:	 128.0 	=> 	 1730
Frequency of value:	 129.0 	=> 	 727
Frequency of value:	 130.0 	=> 	 10388
Frequency of value:	 131.0 	=> 	 422
Frequency of value:	 132.0 	=> 	 1610
Frequency of value:	 133.0 	=> 	 964
Frequency of value:	 134.0 	=> 	 1100
Frequency of value:	 135.0 	=> 	 8496
Frequency of value:	 136.0 	=> 	 1087
Frequency of value:	 137.0 	=> 	 1167
Frequency of value:	 138.0 	=> 	 2075
Frequency of value:	 139.0 	=> 	 718
Frequency of value:	 140.0 	=> 	 13511
Frequency of value:	 141.0 	=> 	 531
Frequency of value:	 142.0 	=> 	 1707
Frequency of value:	 143.0 	=> 	 1220
Frequency of value:	 144.0 	=> 	 845
Frequency of value:	 145.0 	=> 	 9082
Frequency of value:	 146.0 	=> 	 969
Frequency of value:	 147.0 	=> 	 1384
Frequency of value:	 148.0 	=> 	 2138
Frequency of value:	 149.0 	=> 	 741
Frequency of value:	 150.0 	=> 	 18460
Frequency of value:	 151.0 	=> 	 543
Frequency of value:	 152.0 	=> 	 1650
Frequency of value:	 153.0 	=> 	 1130
Frequency of value:	 154.0 	=> 	 1301
Frequency of value:	 155.0 	=> 	 8439
Frequency of value:	 156.0 	=> 	 1221
Frequency of value:	 157.0 	=> 	 1259
Frequency of value:	 158.0 	=> 	 2030
Frequency of value:	 159.0 	=> 	 808
Frequency of value:	 160.0 	=> 	 18118
Frequency of value:	 161.0 	=> 	 541
Frequency of value:	 162.0 	=> 	 1932
Frequency of value:	 163.0 	=> 	 1265
Frequency of value:	 164.0 	=> 	 1192
Frequency of value:	 165.0 	=> 	 10887
Frequency of value:	 166.0 	=> 	 629
Frequency of value:	 167.0 	=> 	 1135
Frequency of value:	 168.0 	=> 	 2329
Frequency of value:	 169.0 	=> 	 807
Frequency of value:	 170.0 	=> 	 16571
Frequency of value:	 171.0 	=> 	 568
Frequency of value:	 172.0 	=> 	 1938
Frequency of value:	 173.0 	=> 	 1074
Frequency of value:	 174.0 	=> 	 1216
Frequency of value:	 175.0 	=> 	 11659
Frequency of value:	 176.0 	=> 	 1050
Frequency of value:	 177.0 	=> 	 774
Frequency of value:	 178.0 	=> 	 2056
Frequency of value:	 179.0 	=> 	 852
Frequency of value:	 180.0 	=> 	 19944
Frequency of value:	 181.0 	=> 	 553
Frequency of value:	 182.0 	=> 	 1595
Frequency of value:	 183.0 	=> 	 1152
Frequency of value:	 184.0 	=> 	 1055
Frequency of value:	 185.0 	=> 	 10115
Frequency of value:	 186.0 	=> 	 955
Frequency of value:	 187.0 	=> 	 1123
Frequency of value:	 188.0 	=> 	 1112
Frequency of value:	 189.0 	=> 	 1026
Frequency of value:	 190.0 	=> 	 14016
Frequency of value:	 191.0 	=> 	 421
Frequency of value:	 192.0 	=> 	 1267
Frequency of value:	 193.0 	=> 	 747
Frequency of value:	 194.0 	=> 	 849
Frequency of value:	 195.0 	=> 	 6919
Frequency of value:	 196.0 	=> 	 914
Frequency of value:	 197.0 	=> 	 846
Frequency of value:	 198.0 	=> 	 1858
Frequency of value:	 199.0 	=> 	 589
Frequency of value:	 200.0 	=> 	 21012
Frequency of value:	 201.0 	=> 	 394
Frequency of value:	 202.0 	=> 	 752
Frequency of value:	 203.0 	=> 	 736
Frequency of value:	 204.0 	=> 	 866
Frequency of value:	 205.0 	=> 	 4658
Frequency of value:	 206.0 	=> 	 682
Frequency of value:	 207.0 	=> 	 646
Frequency of value:	 208.0 	=> 	 979
Frequency of value:	 209.0 	=> 	 505
Frequency of value:	 210.0 	=> 	 9581
Frequency of value:	 211.0 	=> 	 337
Frequency of value:	 212.0 	=> 	 1143
Frequency of value:	 213.0 	=> 	 513
Frequency of value:	 214.0 	=> 	 582
Frequency of value:	 215.0 	=> 	 5243
Frequency of value:	 216.0 	=> 	 437
Frequency of value:	 217.0 	=> 	 525
Frequency of value:	 218.0 	=> 	 878
Frequency of value:	 219.0 	=> 	 346
Frequency of value:	 220.0 	=> 	 10429
Frequency of value:	 221.0 	=> 	 256
Frequency of value:	 222.0 	=> 	 507
Frequency of value:	 223.0 	=> 	 373
Frequency of value:	 224.0 	=> 	 390
Frequency of value:	 225.0 	=> 	 4671
Frequency of value:	 226.0 	=> 	 297
Frequency of value:	 227.0 	=> 	 321
Frequency of value:	 228.0 	=> 	 502
Frequency of value:	 229.0 	=> 	 228
Frequency of value:	 230.0 	=> 	 7912
Frequency of value:	 231.0 	=> 	 169
Frequency of value:	 232.0 	=> 	 462
Frequency of value:	 233.0 	=> 	 211
Frequency of value:	 234.0 	=> 	 338
Frequency of value:	 235.0 	=> 	 2969
Frequency of value:	 236.0 	=> 	 288
Frequency of value:	 237.0 	=> 	 253
Frequency of value:	 238.0 	=> 	 512
Frequency of value:	 239.0 	=> 	 178
Frequency of value:	 240.0 	=> 	 6591
Frequency of value:	 241.0 	=> 	 134
Frequency of value:	 242.0 	=> 	 350
Frequency of value:	 243.0 	=> 	 233
Frequency of value:	 244.0 	=> 	 177
Frequency of value:	 245.0 	=> 	 1944
Frequency of value:	 246.0 	=> 	 203
Frequency of value:	 247.0 	=> 	 231
Frequency of value:	 248.0 	=> 	 364
Frequency of value:	 249.0 	=> 	 154
Frequency of value:	 250.0 	=> 	 7516
Frequency of value:	 251.0 	=> 	 112
Frequency of value:	 252.0 	=> 	 243
Frequency of value:	 253.0 	=> 	 153
Frequency of value:	 254.0 	=> 	 189
Frequency of value:	 255.0 	=> 	 1029
Frequency of value:	 256.0 	=> 	 181
Frequency of value:	 257.0 	=> 	 128
Frequency of value:	 258.0 	=> 	 207
Frequency of value:	 259.0 	=> 	 69
Frequency of value:	 260.0 	=> 	 3720
Frequency of value:	 261.0 	=> 	 74
Frequency of value:	 262.0 	=> 	 190
Frequency of value:	 263.0 	=> 	 140
Frequency of value:	 264.0 	=> 	 116
Frequency of value:	 265.0 	=> 	 1274
Frequency of value:	 266.0 	=> 	 89
Frequency of value:	 267.0 	=> 	 118
Frequency of value:	 268.0 	=> 	 176
Frequency of value:	 269.0 	=> 	 98
Frequency of value:	 270.0 	=> 	 2292
Frequency of value:	 271.0 	=> 	 61
Frequency of value:	 272.0 	=> 	 153
Frequency of value:	 273.0 	=> 	 102
Frequency of value:	 274.0 	=> 	 101
Frequency of value:	 275.0 	=> 	 1393
Frequency of value:	 276.0 	=> 	 84
Frequency of value:	 277.0 	=> 	 63
Frequency of value:	 278.0 	=> 	 118
Frequency of value:	 279.0 	=> 	 66
Frequency of value:	 280.0 	=> 	 2424
Frequency of value:	 281.0 	=> 	 54
Frequency of value:	 282.0 	=> 	 89
Frequency of value:	 283.0 	=> 	 75
Frequency of value:	 284.0 	=> 	 69
Frequency of value:	 285.0 	=> 	 712
Frequency of value:	 286.0 	=> 	 84
Frequency of value:	 287.0 	=> 	 76
Frequency of value:	 288.0 	=> 	 48
Frequency of value:	 289.0 	=> 	 93
Frequency of value:	 290.0 	=> 	 1198
Frequency of value:	 291.0 	=> 	 39
Frequency of value:	 292.0 	=> 	 82
Frequency of value:	 293.0 	=> 	 52
Frequency of value:	 294.0 	=> 	 55
Frequency of value:	 295.0 	=> 	 405
Frequency of value:	 296.0 	=> 	 64
Frequency of value:	 297.0 	=> 	 70
Frequency of value:	 298.0 	=> 	 106
Frequency of value:	 299.0 	=> 	 43
Frequency of value:	 300.0 	=> 	 2441
Frequency of value:	 301.0 	=> 	 29
Frequency of value:	 302.0 	=> 	 55
Frequency of value:	 303.0 	=> 	 35
Frequency of value:	 304.0 	=> 	 40
Frequency of value:	 305.0 	=> 	 193
Frequency of value:	 306.0 	=> 	 38
Frequency of value:	 307.0 	=> 	 43
Frequency of value:	 308.0 	=> 	 44
Frequency of value:	 309.0 	=> 	 39
Frequency of value:	 310.0 	=> 	 444
Frequency of value:	 311.0 	=> 	 29
Frequency of value:	 312.0 	=> 	 64
Frequency of value:	 313.0 	=> 	 24
Frequency of value:	 314.0 	=> 	 39
Frequency of value:	 315.0 	=> 	 257
Frequency of value:	 316.0 	=> 	 22
Frequency of value:	 317.0 	=> 	 22
Frequency of value:	 318.0 	=> 	 48
Frequency of value:	 319.0 	=> 	 29
Frequency of value:	 320.0 	=> 	 605
Frequency of value:	 321.0 	=> 	 10
Frequency of value:	 322.0 	=> 	 24
Frequency of value:	 323.0 	=> 	 27
Frequency of value:	 324.0 	=> 	 25
Frequency of value:	 325.0 	=> 	 316
Frequency of value:	 326.0 	=> 	 34
Frequency of value:	 327.0 	=> 	 18
Frequency of value:	 328.0 	=> 	 25
Frequency of value:	 329.0 	=> 	 17
Frequency of value:	 330.0 	=> 	 354
Frequency of value:	 331.0 	=> 	 11
Frequency of value:	 332.0 	=> 	 13
Frequency of value:	 333.0 	=> 	 14

Frequency of value:	 355.0 	=> 	 24
Frequency of value:	 356.0 	=> 	 6
Frequency of value:	 357.0 	=> 	 4
Frequency of value:	 358.0 	=> 	 7
Frequency of value:	 359.0 	=> 	 5
Frequency of value:	 360.0 	=> 	 172
Frequency of value:	 362.0 	=> 	 11
Frequency of value:	 363.0 	=> 	 3
Frequency of value:	 364.0 	=> 	 5
Frequency of value:	 365.0 	=> 	 51
Frequency of value:	 366.0 	=> 	 5
Frequency of value:	 367.0 	=> 	 3
Frequency of value:	 368.0 	=> 	 6
Frequency of value:	 369.0 	=> 	 8
Frequency of value:	 370.0 	=> 	 117
Frequency of value:	 371.0 	=> 	 2
Frequency of value:	 372.0 	=> 	 5
Frequency of value:	 373.0 	=> 	 4
Frequency of value:	 374.0 	=> 	 4
Frequency of value:	 375.0 	=> 	 75
Frequency of value:	 376.0 	=> 	 4
Frequency of value:	 378.0 	=> 	 5
Frequency of value:	 379.0 	=> 	 3
Frequency of value:	 380.0 	=> 	 125
Frequency of value:	 381.0 	=> 	 3
Frequency of value:	 382.0 	=> 	 4
Frequency of value:	 383.0 	=> 	 7
Frequency of value:	 384.0 	=> 	 4
Frequency of value:	 385.0 	=> 	 32
Frequency of value:	 386.0 	=> 	 8
Frequency of value:	 387.0 	=> 	 3
Frequency of value:	 388.0 	=> 	 3
Frequency of value:	 389.0 	=> 	 2
Frequency of value:	 390.0 	=> 	 50
Frequency of value:	 391.0 	=> 	 2
Frequency of value:	 392.0 	=> 	 3
Frequency of value:	 393.0 	=> 	 4
Frequency of value:	 394.0 	=> 	 3
Frequency of value:	 395.0 	=> 	 11
Frequency of value:	 398.0 	=> 	 7
Frequency of value:	 399.0 	=> 	 2
Frequency of value:	 400.0 	=> 	 184
Frequency of value:	 401.0 	=> 	 2
Frequency of value:	 402.0 	=> 	 10
Frequency of value:	 403.0 	=> 	 2
Frequency of value:	 404.0 	=> 	 2
Frequency of value:	 405.0 	=> 	 3
Frequency of value:	 406.0 	=> 	 2
Frequency of value:	 407.0 	=> 	 3
Frequency of value:	 408.0 	=> 	 3
Frequency of value:	 410.0 	=> 	 22
Frequency of value:	 411.0 	=> 	 4
Frequency of value:	 412.0 	=> 	 6
Frequency of value:	 415.0 	=> 	 12
Frequency of value:	 416.0 	=> 	 4
Frequency of value:	 417.0 	=> 	 5
Frequency of value:	 418.0 	=> 	 5
Frequency of value:	 419.0 	=> 	 5
Frequency of value:	 420.0 	=> 	 33
Frequency of value:	 422.0 	=> 	 2
Frequency of value:	 423.0 	=> 	 3
Frequency of value:	 425.0 	=> 	 20
Frequency of value:	 426.0 	=> 	 5
Frequency of value:	 430.0 	=> 	 19
Frequency of value:	 434.0 	=> 	 2
Frequency of value:	 435.0 	=> 	 4
Frequency of value:	 436.0 	=> 	 2
Frequency of value:	 439.0 	=> 	 3
Frequency of value:	 440.0 	=> 	 20
Frequency of value:	 444.0 	=> 	 3
Frequency of value:	 445.0 	=> 	 4
Frequency of value:	 448.0 	=> 	 2
Frequency of value:	 450.0 	=> 	 44
Frequency of value:	 455.0 	=> 	 3
Frequency of value:	 456.0 	=> 	 2
Frequency of value:	 460.0 	=> 	 11
Frequency of value:	 465.0 	=> 	 6
Frequency of value:	 469.0 	=> 	 2
Frequency of value:	 470.0 	=> 	 10
Frequency of value:	 475.0 	=> 	 2
Frequency of value:	 480.0 	=> 	 9
Frequency of value:	 483.0 	=> 	 4
Frequency of value:	 485.0 	=> 	 4
Frequency of value:	 486.0 	=> 	 2
Frequency of value:	 490.0 	=> 	 2
Frequency of value:	 494.0 	=> 	 2
Frequency of value:	 500.0 	=> 	 30
Frequency of value:	 505.0 	=> 	 3
Frequency of value:	 508.0 	=> 	 3
Frequency of value:	 511.0 	=> 	 2
Frequency of value:	 520.0 	=> 	 2
Frequency of value:	 525.0 	=> 	 5
Frequency of value:	 530.0 	=> 	 6
Frequency of value:	 550.0 	=> 	 6
Frequency of value:	 600.0 	=> 	 13
Frequency of value:	 777.0 	=> 	 3
Frequency of value:	 7777.0 	=> 	 6908
Frequency of value:	 9025.0 	=> 	 2
Frequency of value:	 9030.0 	=> 	 2
Frequency of value:	 9034.0 	=> 	 2
Frequency of value:	 9042.0 	=> 	 2
Frequency of value:	 9045.0 	=> 	 11
Frequency of value:	 9048.0 	=> 	 13
Frequency of value:	 9049.0 	=> 	 3
Frequency of value:	 9050.0 	=> 	 32
Frequency of value:	 9051.0 	=> 	 7
Frequency of value:	 9052.0 	=> 	 17
Frequency of value:	 9053.0 	=> 	 26
Frequency of value:	 9054.0 	=> 	 16
Frequency of value:	 9055.0 	=> 	 22
Frequency of value:	 9056.0 	=> 	 22
Frequency of value:	 9057.0 	=> 	 15
Frequency of value:	 9058.0 	=> 	 20
Frequency of value:	 9059.0 	=> 	 13
Frequency of value:	 9060.0 	=> 	 61
Frequency of value:	 9061.0 	=> 	 10
Frequency of value:	 9062.0 	=> 	 26
Frequency of value:	 9063.0 	=> 	 18
Frequency of value:	 9064.0 	=> 	 25
Frequency of value:	 9065.0 	=> 	 74
Frequency of value:	 9066.0 	=> 	 11
Frequency of value:	 9067.0 	=> 	 22
Frequency of value:	 9068.0 	=> 	 28
Frequency of value:	 9069.0 	=> 	 12
Frequency of value:	 9070.0 	=> 	 86
Frequency of value:	 9071.0 	=> 	 14
Frequency of value:	 9072.0 	=> 	 52
Frequency of value:	 9073.0 	=> 	 24
Frequency of value:	 9074.0 	=> 	 19
Frequency of value:	 9075.0 	=> 	 71
Frequency of value:	 9076.0 	=> 	 19
Frequency of value:	 9077.0 	=> 	 15
Frequency of value:	 9078.0 	=> 	 29
Frequency of value:	 9079.0 	=> 	 8
Frequency of value:	 9080.0 	=> 	 47
Frequency of value:	 9081.0 	=> 	 7
Frequency of value:	 9082.0 	=> 	 32
Frequency of value:	 9083.0 	=> 	 16
Frequency of value:	 9084.0 	=> 	 13
Frequency of value:	 9085.0 	=> 	 30
Frequency of value:	 9086.0 	=> 	 16
Frequency of value:	 9087.0 	=> 	 7
Frequency of value:	 9088.0 	=> 	 9
Frequency of value:	 9089.0 	=> 	 7
Frequency of value:	 9090.0 	=> 	 30
Frequency of value:	 9091.0 	=> 	 2
Frequency of value:	 9092.0 	=> 	 10
Frequency of value:	 9093.0 	=> 	 4
Frequency of value:	 9094.0 	=> 	 8
Frequency of value:	 9095.0 	=> 	 9
Frequency of value:	 9096.0 	=> 	 4
Frequency of value:	 9097.0 	=> 	 2
Frequency of value:	 9098.0 	=> 	 3
Frequency of value:	 9100.0 	=> 	 14
Frequency of value:	 9102.0 	=> 	 2
Frequency of value:	 9103.0 	=> 	 2
Frequency of value:	 9104.0 	=> 	 3
Frequency of value:	 9105.0 	=> 	 6
Frequency of value:	 9106.0 	=> 	 2
Frequency of value:	 9107.0 	=> 	 3
Frequency of value:	 9108.0 	=> 	 2
Frequency of value:	 9109.0 	=> 	 2
Frequency of value:	 9110.0 	=> 	 5
Frequency of value:	 9112.0 	=> 	 4
Frequency of value:	 9115.0 	=> 	 3
Frequency of value:	 9120.0 	=> 	 5
Frequency of value:	 9130.0 	=> 	 4
Frequency of value:	 9132.0 	=> 	 2
Frequency of value:	 9150.0 	=> 	 6
Frequency of value:	 9155.0 	=> 	 3
Frequency of value:	 9156.0 	=> 	 2
Frequency of value:	 9157.0 	=> 	 2
Frequency of value:	 9170.0 	=> 	 2
Frequency of value:	 9175.0 	=> 	 3
Frequency of value:	 9180.0 	=> 	 2
Frequency of value:	 9190.0 	=> 	 2
Frequency of value:	 9200.0 	=> 	 3
Frequency of value:	 9210.0 	=> 	 2
Frequency of value:	 9230.0 	=> 	 2
Frequency of value:	 9352.0 	=> 	 2
Frequency of value:	 9999.0 	=> 	 15204

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  HEIGHT3

Number of Unique values for the given column:  152

Unique Values:
 [ 504.  505.  410.  510.  503.  502.  601.  600.  511.  506.  509.  507.
  603.  508.  602.  500. 9999.  501. 7777.  408.  411.  607.  604.   nan
  605.  404.  409.  608.  406.  609. 9170.  606.  708.  611.  701.  610.
  403. 9090.  407. 9156. 9150. 9168.  405. 9154. 9155. 9160. 9176. 9105.
 9163. 9180. 9152. 9147. 9162. 9200.  702. 9159. 9145. 9175. 9179.  305.
  300. 9172. 9177. 9178.  700. 9165. 9169. 9167. 9164.  550.  402.  705.
 1100. 9173. 9153. 9196. 9148. 9158. 9157. 9140. 9166. 9184. 9174.  400.
  711.  307. 9185. 9116. 9203.  710. 9142. 9151. 9183.  401. 9192. 9161.
 9186. 9181. 9108. 9171. 9111.  200. 9149. 9195.  306. 9104. 9190.  309.
 9107.  311.  301. 9182. 9198. 9118. 9110.  308. 9130.  706. 9187. 9125.
 9320. 9193. 9146.  703. 9136. 9120. 9103. 9106. 9135. 9189. 9205. 9208.
 9115. 9143. 9202. 9188. 9102. 9100. 9122. 9137. 9144. 9117. 9250.  304.
  707.  709.  310.  800. 9109. 9128. 9206.  704.]

Frequency of value:	 300.0 	=> 	 80
Frequency of value:	 301.0 	=> 	 3
Frequency of value:	 304.0 	=> 	 4
Frequency of value:	 305.0 	=> 	 7
Frequency of value:	 306.0 	=> 	 5
Frequency of value:	 307.0 	=> 	 2
Frequency of value:	 309.0 	=> 	 4
Frequency of value:	 311.0 	=> 	 8
Frequency of value:	 400.0 	=> 	 80
Frequency of value:	 401.0 	=> 	 29
Frequency of value:	 402.0 	=> 	 38
Frequency of value:	 403.0 	=> 	 30
Frequency of value:	 404.0 	=> 	 31
Frequency of value:	 405.0 	=> 	 125
Frequency of value:	 406.0 	=> 	 85
Frequency of value:	 407.0 	=> 	 113
Frequency of value:	 408.0 	=> 	 397
Frequency of value:	 409.0 	=> 	 819
Frequency of value:	 410.0 	=> 	 1487
Frequency of value:	 411.0 	=> 	 4424
Frequency of value:	 500.0 	=> 	 14525
Frequency of value:	 501.0 	=> 	 14690
Frequency of value:	 502.0 	=> 	 28669
Frequency of value:	 503.0 	=> 	 30370
Frequency of value:	 504.0 	=> 	 37114
Frequency of value:	 505.0 	=> 	 33189
Frequency of value:	 506.0 	=> 	 37675
Frequency of value:	 507.0 	=> 	 34054
Frequency of value:	 508.0 	=> 	 31154
Frequency of value:	 509.0 	=> 	 28574
Frequency of value:	 510.0 	=> 	 31013
Frequency of value:	 511.0 	=> 	 24404
Frequency of value:	 600.0 	=> 	 27850
Frequency of value:	 601.0 	=> 	 13515
Frequency of value:	 602.0 	=> 	 11331
Frequency of value:	 603.0 	=> 	 6179
Frequency of value:	 604.0 	=> 	 3936
Frequency of value:	 605.0 	=> 	 1599
Frequency of value:	 606.0 	=> 	 806
Frequency of value:	 607.0 	=> 	 377
Frequency of value:	 608.0 	=> 	 251
Frequency of value:	 609.0 	=> 	 63
Frequency of value:	 610.0 	=> 	 44
Frequency of value:	 611.0 	=> 	 26
Frequency of value:	 700.0 	=> 	 25
Frequency of value:	 701.0 	=> 	 16
Frequency of value:	 702.0 	=> 	 4
Frequency of value:	 703.0 	=> 	 5
Frequency of value:	 705.0 	=> 	 8
Frequency of value:	 706.0 	=> 	 5
Frequency of value:	 707.0 	=> 	 2
Frequency of value:	 708.0 	=> 	 3
Frequency of value:	 711.0 	=> 	 7
Frequency of value:	 7777.0 	=> 	 3780
Frequency of value:	 9090.0 	=> 	 7
Frequency of value:	 9100.0 	=> 	 2
Frequency of value:	 9102.0 	=> 	 2
Frequency of value:	 9103.0 	=> 	 4
Frequency of value:	 9104.0 	=> 	 11
Frequency of value:	 9105.0 	=> 	 29
Frequency of value:	 9106.0 	=> 	 3
Frequency of value:	 9107.0 	=> 	 6
Frequency of value:	 9110.0 	=> 	 3
Frequency of value:	 9116.0 	=> 	 2
Frequency of value:	 9118.0 	=> 	 2
Frequency of value:	 9120.0 	=> 	 3
Frequency of value:	 9125.0 	=> 	 4
Frequency of value:	 9130.0 	=> 	 7
Frequency of value:	 9135.0 	=> 	 8
Frequency of value:	 9136.0 	=> 	 3
Frequency of value:	 9140.0 	=> 	 16
Frequency of value:	 9142.0 	=> 	 3
Frequency of value:	 9145.0 	=> 	 10
Frequency of value:	 9146.0 	=> 	 3
Frequency of value:	 9147.0 	=> 	 7
Frequency of value:	 9148.0 	=> 	 9
Frequency of value:	 9149.0 	=> 	 9
Frequency of value:	 9150.0 	=> 	 93
Frequency of value:	 9151.0 	=> 	 13
Frequency of value:	 9152.0 	=> 	 44
Frequency of value:	 9153.0 	=> 	 27
Frequency of value:	 9154.0 	=> 	 30
Frequency of value:	 9155.0 	=> 	 68
Frequency of value:	 9156.0 	=> 	 34
Frequency of value:	 9157.0 	=> 	 23
Frequency of value:	 9158.0 	=> 	 29
Frequency of value:	 9159.0 	=> 	 18
Frequency of value:	 9160.0 	=> 	 142
Frequency of value:	 9161.0 	=> 	 16
Frequency of value:	 9162.0 	=> 	 47
Frequency of value:	 9163.0 	=> 	 50
Frequency of value:	 9164.0 	=> 	 34
Frequency of value:	 9165.0 	=> 	 117
Frequency of value:	 9166.0 	=> 	 24
Frequency of value:	 9167.0 	=> 	 36
Frequency of value:	 9168.0 	=> 	 42
Frequency of value:	 9169.0 	=> 	 26
Frequency of value:	 9170.0 	=> 	 148
Frequency of value:	 9171.0 	=> 	 7
Frequency of value:	 9172.0 	=> 	 51
Frequency of value:	 9173.0 	=> 	 44
Frequency of value:	 9174.0 	=> 	 16
Frequency of value:	 9175.0 	=> 	 106
Frequency of value:	 9176.0 	=> 	 34
Frequency of value:	 9177.0 	=> 	 21
Frequency of value:	 9178.0 	=> 	 37
Frequency of value:	 9179.0 	=> 	 20
Frequency of value:	 9180.0 	=> 	 73
Frequency of value:	 9181.0 	=> 	 6
Frequency of value:	 9182.0 	=> 	 11
Frequency of value:	 9183.0 	=> 	 16
Frequency of value:	 9184.0 	=> 	 11
Frequency of value:	 9185.0 	=> 	 11
Frequency of value:	 9186.0 	=> 	 5
Frequency of value:	 9187.0 	=> 	 4
Frequency of value:	 9190.0 	=> 	 8
Frequency of value:	 9192.0 	=> 	 2
Frequency of value:	 9205.0 	=> 	 4
Frequency of value:	 9999.0 	=> 	 5471

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  PREGNANT

Number of Unique values for the given column:  5

Unique Values:
 [nan  2.  9.  1.  7.]

Frequency of value:	 1.0 	=> 	 2403
Frequency of value:	 2.0 	=> 	 75110
Frequency of value:	 7.0 	=> 	 228
Frequency of value:	 9.0 	=> 	 669

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  HADHYST2

Number of Unique values for the given column:  5

Unique Values:
 [ 1.  2. nan  9.  7.]

Frequency of value:	 1.0 	=> 	 63145
Frequency of value:	 2.0 	=> 	 159364
Frequency of value:	 7.0 	=> 	 504
Frequency of value:	 9.0 	=> 	 681

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  COPDCOGH

Number of Unique values for the given column:  5

Unique Values:
 [ 2.  1. nan  9.  7.]

Frequency of value:	 1.0 	=> 	 14335
Frequency of value:	 2.0 	=> 	 66386
Frequency of value:	 7.0 	=> 	 246
Frequency of value:	 9.0 	=> 	 65

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  COPDFLEM

Number of Unique values for the given column:  5

Unique Values:
 [ 2.  1. nan  7.  9.]

Frequency of value:	 1.0 	=> 	 12192
Frequency of value:	 2.0 	=> 	 69152
Frequency of value:	 7.0 	=> 	 264
Frequency of value:	 9.0 	=> 	 60

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  COPDBRTH

Number of Unique values for the given column:  5

Unique Values:
 [ 2.  1. nan  7.  9.]

Frequency of value:	 1.0 	=> 	 22267
Frequency of value:	 2.0 	=> 	 58932
Frequency of value:	 7.0 	=> 	 339
Frequency of value:	 9.0 	=> 	 71

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  CNCRAGE

Number of Unique values for the given column:  98

Unique Values:
 [nan 60. 71. 50. 98. 69. 78. 64. 59. 73. 77. 40. 47. 16. 66. 62. 17. 63.
 55. 41. 56. 48. 58. 65. 61. 81. 54. 38. 30. 70. 75. 45. 35. 46. 42. 33.
 22. 68. 86. 82. 39. 57. 32. 89. 19. 49. 74. 79. 67.  5. 28. 20. 51. 53.
 52. 72. 95. 27. 80. 37. 43. 25. 44. 84. 36. 34. 29. 31. 83. 24. 21.  2.
 18. 23. 99. 26. 76. 85. 15. 87. 14. 94. 10.  4. 91.  6.  9. 90. 92.  3.
 93. 88. 13. 12.  7.  1. 11. 97.]

Frequency of value:	 1.0 	=> 	 3
Frequency of value:	 2.0 	=> 	 4
Frequency of value:	 3.0 	=> 	 3
Frequency of value:	 4.0 	=> 	 2
Frequency of value:	 5.0 	=> 	 3
Frequency of value:	 9.0 	=> 	 3
Frequency of value:	 10.0 	=> 	 3
Frequency of value:	 11.0 	=> 	 2
Frequency of value:	 12.0 	=> 	 2
Frequency of value:	 13.0 	=> 	 4
Frequency of value:	 14.0 	=> 	 5
Frequency of value:	 15.0 	=> 	 9
Frequency of value:	 16.0 	=> 	 9
Frequency of value:	 17.0 	=> 	 13
Frequency of value:	 18.0 	=> 	 12
Frequency of value:	 19.0 	=> 	 20
Frequency of value:	 20.0 	=> 	 28
Frequency of value:	 21.0 	=> 	 16
Frequency of value:	 22.0 	=> 	 23
Frequency of value:	 23.0 	=> 	 27
Frequency of value:	 24.0 	=> 	 27
Frequency of value:	 25.0 	=> 	 45
Frequency of value:	 26.0 	=> 	 15
Frequency of value:	 27.0 	=> 	 23
Frequency of value:	 28.0 	=> 	 33
Frequency of value:	 29.0 	=> 	 18
Frequency of value:	 30.0 	=> 	 85
Frequency of value:	 31.0 	=> 	 12
Frequency of value:	 32.0 	=> 	 39
Frequency of value:	 33.0 	=> 	 36
Frequency of value:	 34.0 	=> 	 32
Frequency of value:	 35.0 	=> 	 89
Frequency of value:	 36.0 	=> 	 46
Frequency of value:	 37.0 	=> 	 33
Frequency of value:	 38.0 	=> 	 50
Frequency of value:	 39.0 	=> 	 34
Frequency of value:	 40.0 	=> 	 188
Frequency of value:	 41.0 	=> 	 38
Frequency of value:	 42.0 	=> 	 84
Frequency of value:	 43.0 	=> 	 51
Frequency of value:	 44.0 	=> 	 52
Frequency of value:	 45.0 	=> 	 167
Frequency of value:	 46.0 	=> 	 57
Frequency of value:	 47.0 	=> 	 56
Frequency of value:	 48.0 	=> 	 97
Frequency of value:	 49.0 	=> 	 75
Frequency of value:	 50.0 	=> 	 319
Frequency of value:	 51.0 	=> 	 94
Frequency of value:	 52.0 	=> 	 114
Frequency of value:	 53.0 	=> 	 90
Frequency of value:	 54.0 	=> 	 92
Frequency of value:	 55.0 	=> 	 247
Frequency of value:	 56.0 	=> 	 96
Frequency of value:	 57.0 	=> 	 113
Frequency of value:	 58.0 	=> 	 137
Frequency of value:	 59.0 	=> 	 105
Frequency of value:	 60.0 	=> 	 325
Frequency of value:	 61.0 	=> 	 102
Frequency of value:	 62.0 	=> 	 166
Frequency of value:	 63.0 	=> 	 121
Frequency of value:	 64.0 	=> 	 144
Frequency of value:	 65.0 	=> 	 299
Frequency of value:	 66.0 	=> 	 108
Frequency of value:	 67.0 	=> 	 118
Frequency of value:	 68.0 	=> 	 100
Frequency of value:	 69.0 	=> 	 98
Frequency of value:	 70.0 	=> 	 235
Frequency of value:	 71.0 	=> 	 78
Frequency of value:	 72.0 	=> 	 97
Frequency of value:	 73.0 	=> 	 84
Frequency of value:	 74.0 	=> 	 69
Frequency of value:	 75.0 	=> 	 168
Frequency of value:	 76.0 	=> 	 67
Frequency of value:	 77.0 	=> 	 54
Frequency of value:	 78.0 	=> 	 53
Frequency of value:	 79.0 	=> 	 42
Frequency of value:	 80.0 	=> 	 79
Frequency of value:	 81.0 	=> 	 27
Frequency of value:	 82.0 	=> 	 35
Frequency of value:	 83.0 	=> 	 24
Frequency of value:	 84.0 	=> 	 14
Frequency of value:	 85.0 	=> 	 31
Frequency of value:	 86.0 	=> 	 9
Frequency of value:	 87.0 	=> 	 11
Frequency of value:	 88.0 	=> 	 11
Frequency of value:	 89.0 	=> 	 7
Frequency of value:	 90.0 	=> 	 10
Frequency of value:	 91.0 	=> 	 3
Frequency of value:	 93.0 	=> 	 2
Frequency of value:	 94.0 	=> 	 3
Frequency of value:	 98.0 	=> 	 289
Frequency of value:	 99.0 	=> 	 23

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  CNCRTYP1

Number of Unique values for the given column:  33

Unique Values:
 [nan 22. 19. 21.  1. 30. 10.  8. 77. 24.  2. 12.  5.  4. 20. 25.  3. 14.
 16. 26.  6. 27. 17. 11.  9. 15.  7. 29. 23. 13. 18. 28. 99.]

Frequency of value:	 1.0 	=> 	 911
Frequency of value:	 2.0 	=> 	 227
Frequency of value:	 3.0 	=> 	 132
Frequency of value:	 4.0 	=> 	 75
Frequency of value:	 5.0 	=> 	 16
Frequency of value:	 6.0 	=> 	 21
Frequency of value:	 7.0 	=> 	 21
Frequency of value:	 8.0 	=> 	 120
Frequency of value:	 9.0 	=> 	 5
Frequency of value:	 10.0 	=> 	 218
Frequency of value:	 11.0 	=> 	 17
Frequency of value:	 12.0 	=> 	 26
Frequency of value:	 13.0 	=> 	 15
Frequency of value:	 14.0 	=> 	 26
Frequency of value:	 15.0 	=> 	 17
Frequency of value:	 16.0 	=> 	 47
Frequency of value:	 17.0 	=> 	 66
Frequency of value:	 18.0 	=> 	 69
Frequency of value:	 19.0 	=> 	 552
Frequency of value:	 20.0 	=> 	 26
Frequency of value:	 21.0 	=> 	 804
Frequency of value:	 22.0 	=> 	 1703
Frequency of value:	 23.0 	=> 	 3
Frequency of value:	 24.0 	=> 	 151
Frequency of value:	 25.0 	=> 	 131
Frequency of value:	 26.0 	=> 	 91
Frequency of value:	 27.0 	=> 	 28
Frequency of value:	 28.0 	=> 	 16
Frequency of value:	 29.0 	=> 	 3
Frequency of value:	 30.0 	=> 	 332
Frequency of value:	 77.0 	=> 	 292
Frequency of value:	 99.0 	=> 	 26

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  CSRVTRT2

Number of Unique values for the given column:  8

Unique Values:
 [nan  2.  5.  1.  3.  4.  9.  7.]

Frequency of value:	 1.0 	=> 	 746
Frequency of value:	 2.0 	=> 	 3786
Frequency of value:	 3.0 	=> 	 74
Frequency of value:	 4.0 	=> 	 319
Frequency of value:	 5.0 	=> 	 1108
Frequency of value:	 7.0 	=> 	 128
Frequency of value:	 9.0 	=> 	 23

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  _IMPRACE

Number of Unique values for the given column:  6

Unique Values:
 [1. 2. 6. 5. 3. 4.]

Frequency of value:	 1.0 	=> 	 329914
Frequency of value:	 2.0 	=> 	 36443
Frequency of value:	 3.0 	=> 	 10884
Frequency of value:	 4.0 	=> 	 8534
Frequency of value:	 5.0 	=> 	 37319
Frequency of value:	 6.0 	=> 	 14342

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  _AGEG5YR

Number of Unique values for the given column:  14

Unique Values:
 [13.  3. 12. 10.  5.  6.  8. 11.  7.  4.  9. 14.  1.  2.]

Frequency of value:	 1.0 	=> 	 26005
Frequency of value:	 2.0 	=> 	 22286
Frequency of value:	 3.0 	=> 	 24269
Frequency of value:	 4.0 	=> 	 26118
Frequency of value:	 5.0 	=> 	 25583
Frequency of value:	 6.0 	=> 	 28846
Frequency of value:	 7.0 	=> 	 35060
Frequency of value:	 8.0 	=> 	 42160
Frequency of value:	 9.0 	=> 	 46994
Frequency of value:	 10.0 	=> 	 47329
Frequency of value:	 11.0 	=> 	 40930
Frequency of value:	 12.0 	=> 	 28668
Frequency of value:	 13.0 	=> 	 34716
Frequency of value:	 14.0 	=> 	 8472

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Analysis for column:  DIABETE3

Number of Unique values for the given column:  7

Unique Values:
 [ 3.  1.  4.  2.  9. nan  7.]

Frequency of value:	 1.0 	=> 	 60703
Frequency of value:	 2.0 	=> 	 3857
Frequency of value:	 3.0 	=> 	 363757
Frequency of value:	 4.0 	=> 	 8263
Frequency of value:	 7.0 	=> 	 567
Frequency of value:	 9.0 	=> 	 265

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

#### Rename Columns

In [11]:
# axis='columns' or axis=1 is to rename column names
# inplace=True is to rename the existing DataFrame (rather than creating a copy) 
# errors="raise" is to raise errors if an invalid column-to-rename is specified

for data in [df_clean]:
    data.rename({'DIABETE3': 'DIABETES', 
                 'EXERANY2': 'EXERCISE', 
                 'SLEPTIM1': 'SLEEPTIME',  
                 'CVDINFR4': 'HEARTATTACK', 
                 'CVDCRHD4': 'CORONARYHEARTDISEASE', 
                 'CVDSTRK3': 'STROKE', 
                 'ASTHMA3': 'ASTHMA', 
                 'ASTHNOW': 'ASTHMANOW', 
                 'CHCSCNCR': 'SKINCANCER', 
                 'CHCOCNCR': 'OTHERCANCER', 
                 'CHCCOPD1': 'CHRONICBRONCHITIS', 
                 'HAVARTH3': 'ARTHRITIS', 
                 'ADDEPEV2': 'DEPRESSIVEDISORDER', 
                 'CHCKDNY1': 'KIDNEYDISEASE',   
                 'SEX1': 'SEX',
                 'WEIGHT2': 'WEIGHT',
                 'HEIGHT3': 'HEIGHT',
                 'PREGNANT': 'PREGNANT',
                 'HADHYST2': 'HYSTERECTOMY',
                 'COPDCOGH': 'COUGH',
                 'COPDFLEM': 'COUGHMUCUS',
                 'COPDBRTH': 'SHORTBREATH',
                 'CNCRAGE': 'CANCERAGE',
                 'CNCRTYP1': 'CANCERTYPE',
                 'CSRVTRT2': 'CANCERTREATMENT',
                 '_IMPRACE': 'RACE',
                 '_AGEG5YR': 'AGE'}, axis='columns', inplace=True, errors="raise")

#### Define Functions for Data Cleaning

In [12]:
# Create Function for sorting out Yes/No Features
def cleanFeature(num):
    if num == 1:
        return 1
    elif num == 2:
        return 0
    else:
        return np.nan

#### Define Functions for Data Engineering

In [13]:
# Create Function for sorting out SLEEPTIME into SLEEPTIME_GROUP
def getSleepTimeGroup(time):
    if time <= 6:
        return 'LessSleep'
    elif time >= 7 and time <= 9:
        return 'NormalSleep'
    elif time >= 10:
        return 'OverSleep'
    else:
        return np.nan

In [14]:
# Create Function for sorting out SEX into SEX_GROUP
def getSexGroup(num):
    if num == 1:
        return 'Male'
    elif num == 2:
        return 'Female'
    else:
        return np.nan

In [15]:
# Create Function for converting WEIGHT into WEIGHT_KILOGRAM
def getWeightInKilogram(num):
    if np.isnan(num):
        return np.nan
        
    num = str(int(num))
    
    if num[0] == '9' and num != '9999':
        return float(num[1:])
    elif num != '9999' and num != '7777':
        return round(0.453592 * float(num), 3)
    else:
        return np.nan

In [16]:
# Create Function for converting HEIGHT into HEIGHT_METER
def getHeightInMeter(num):
    if np.isnan(num):
        return np.nan
    
    num = str(int(num))

    if num[0] == '9' and num != '9999':
        return float(num[1:]) / 100 # centimeter to meter
    elif num != '9999' and num != '7777':
        return round((float(num[0])*12 + float(num[1:]))*0.0254, 3)
    else:
        return np.nan

In [17]:
# Create Function for sorting out BMI into BMI_GROUP
def getBMIGroup(bmi):
    if bmi < 1850:
        return 'UnderWeight'
    elif bmi >= 1850 and bmi < 2500:
        return 'NormalWeight'
    elif bmi >= 2500 and bmi < 3000:
        return 'OverWeight'
    elif bmi >= 3000 and bmi < 9999:
        return 'Obese'    
    else:
        return np.nan

In [18]:
# Create Function for sorting out RACE into RACE_GROUP
def getRaceGroup(num):
    if num == 1:
        return 'White'
    elif num == 2:
        return 'Black'
    elif num == 3:
        return 'Asian'
    elif num == 4:
        return 'AmericanIndian'
    elif num == 5:
        return 'Hispanic' 
    elif num == 6:
        return 'Other'
    else:
        return np.nan

In [19]:
# Create Function for sorting out AGE into AGE_GROUP
def getAgeGroup(age):
    if age < 4:                 # 1: 18-24, 2: 25-29, 3: 30-34
        return 'YoungAdult'         
    elif age >= 4 and age < 7:  # 4: 35-30, 5: 40-44, 6: 45-49   
        return 'Adult'              
    elif age >= 7 and age < 10: # 7: 50-54, 8: 55-59, 9: 60-64
        return 'OldAdult'  
    elif age >= 10:             # 10: 65-69 11: 70-74, 12: 75-79, 13: 80+
        return 'Elderly'   
    else:
        return np.nan

#### Clean Existing Columns

In [20]:
# Clean existing features
for data in [df_clean]:
    
    # Clean EXERCISE Feature
    data['EXERCISE'] = data['EXERCISE'].apply(lambda x: cleanFeature(x))
    
    # Clean HEARTATTACK Feature
    data['HEARTATTACK'] = data['HEARTATTACK'].apply(lambda x: cleanFeature(x))
    
    # Clean CORONARYHEARTDISEASE Feature
    data['CORONARYHEARTDISEASE'] = data['CORONARYHEARTDISEASE'].apply(lambda x: cleanFeature(x))
    
    # Clean STROKE Feature
    data['STROKE'] = data['STROKE'].apply(lambda x: cleanFeature(x))
    
    # Clean ASTHMA Feature
    data['ASTHMA'] = data['ASTHMA'].apply(lambda x: cleanFeature(x))
    
    # Clean ASTHMANOW Feature
    data['ASTHMANOW'] = data['ASTHMANOW'].apply(lambda x: cleanFeature(x))
    
    # Clean SKINCANCER Feature
    data['SKINCANCER'] = data['SKINCANCER'].apply(lambda x: cleanFeature(x))
    
    # Clean OTHERCANCER Feature
    data['OTHERCANCER'] = data['OTHERCANCER'].apply(lambda x: cleanFeature(x))
    
    # Clean CHRONICBRONCHITIS Feature
    data['CHRONICBRONCHITIS'] = data['CHRONICBRONCHITIS'].apply(lambda x: cleanFeature(x))
    
    # Clean ARTHRITIS Feature
    data['ARTHRITIS'] = data['ARTHRITIS'].apply(lambda x: cleanFeature(x))
    
    # Clean DEPRESSIVEDISORDER Feature
    data['DEPRESSIVEDISORDER'] = data['DEPRESSIVEDISORDER'].apply(lambda x: cleanFeature(x))
    
    # Clean KIDNEYDISEASE Feature
    data['KIDNEYDISEASE'] = data['KIDNEYDISEASE'].apply(lambda x: cleanFeature(x))
    
    # Clean PREGNANT Feature
    data['PREGNANT'] = data['PREGNANT'].apply(lambda x: cleanFeature(x))
    
    # Clean HYSTERECTOMY Feature
    data['HYSTERECTOMY'] = data['HYSTERECTOMY'].apply(lambda x: cleanFeature(x))

    # Clean COUGH Feature
    data['COUGH'] = data['COUGH'].apply(lambda x: cleanFeature(x))
    
    # Clean COUGHMUCUS Feature
    data['COUGHMUCUS'] = data['COUGHMUCUS'].apply(lambda x: cleanFeature(x))
    
    # Clean SHORTBREATH Feature
    data['SHORTBREATH'] = data['SHORTBREATH'].apply(lambda x: cleanFeature(x))

#### Engineer New Columns

In [21]:
# Create new features
for data in [df_clean]:
    
    # Create SLEEPTIME_GROUP Feature from SLEEPTIME
    data['SLEEPTIME_GROUP'] = data['SLEEPTIME'].apply(lambda x: getSleepTimeGroup(x))
    
    # Create SEX_GROUP Feature from SEX
    data['SEX_GROUP'] = data['SEX'].apply(lambda x: getSexGroup(x))
    
    # Create WEIGHT_KILOGRAM Feature from WEIGHT
    data['WEIGHT_KILOGRAM'] = data['WEIGHT'].apply(lambda x: getWeightInKilogram(x))
    
    # Create HEIGHT_METER Feature from HEIGHT
    data['HEIGHT_METER'] = data['HEIGHT'].apply(lambda x: getHeightInMeter(x))
    
    # Create BMI Feature from WEIGHT_KILOGRAM and HEIGHT_METER    
    data['BMI'] = data['WEIGHT_KILOGRAM'] / (data['HEIGHT'] * data['HEIGHT'])
    
    # Create BMI_GROUP Feature from BMI    
    data['BMI_GROUP'] = data['BMI'].apply(lambda x: getBMIGroup(x))

    # Create RACE_GROUP Feature from RACE    
    data['RACE_GROUP'] = data['RACE'].apply(lambda x: getRaceGroup(x))
    
    # Create AGE_GROUP Feature from AGE    
    data['AGE_GROUP'] = data['AGE'].apply(lambda x: getAgeGroup(x))

#### Check Missing Values per Column after Data Cleaning & Engineering

In [22]:
for data in [df_clean]:
    print("{} Features with Null Values:\n\n {}\n".format(data.names, data.isnull().sum()))

Diabetes Cleaned Dataset Features with Null Values:

 EXERCISE                   695
SLEEPTIME                   23
HEARTATTACK               2318
CORONARYHEARTDISEASE      3673
STROKE                    1351
ASTHMA                    1415
ASTHMANOW               377503
SKINCANCER                1327
OTHERCANCER               1238
CHRONICBRONCHITIS         2201
ARTHRITIS                 2534
DEPRESSIVEDISORDER        2153
KIDNEYDISEASE             1686
SEX                          0
WEIGHT                    6447
HEIGHT                    7198
PREGNANT                359923
HYSTERECTOMY            214927
COUGH                   356715
COUGHMUCUS              356092
SHORTBREATH             356237
CANCERAGE               431245
CANCERTYPE              431249
CANCERTREATMENT         431252
RACE                         0
AGE                          0
DIABETES                    24
SLEEPTIME_GROUP             23
SEX_GROUP                 1113
WEIGHT_KILOGRAM          28559
HEIGHT_METER             16449
BMI                      28999
BMI_GROUP                28999
RACE_GROUP                   0
AGE_GROUP                    0
dtype: int64

#### Drop Columns

In [23]:
manyMissingVals = ['ASTHMANOW', 'PREGNANT', 'HYSTERECTOMY', 'COUGH', 'COUGHMUCUS', 'SHORTBREATH', 'CANCERAGE',
                  'CANCERTYPE', 'CANCERTREATMENT']

redundantInfo = ['SLEEPTIME', 'SEX', 'WEIGHT', 'HEIGHT', 'BMI', 'RACE', 'AGE']

In [24]:
for data in [df_clean]:
    
    # Drop Cols due to many missing values
    data.drop(manyMissingVals, axis = 1, inplace=True)
    
    # Drop Cols due to redundant information
    data.drop(redundantInfo, axis = 1, inplace=True)

#### Drop Rows

In [25]:
for data in [df_clean]:
    
    # Drop Rows with Nan Values in DIABETES
    data.dropna(subset=['DIABETES'], inplace=True)
    
    # Drop All Rows with Nan Values in Features
    data.dropna(inplace=True)

#### Testing

In [26]:
# Test 1: Check Missing Values per Column after Data Cleaning & Engineering
for data in [df_clean]:
    print("{} Features with Null Values:\n\n {}\n".format(data.names, data.isnull().sum()))

Diabetes Cleaned Dataset Features with Null Values:

 EXERCISE                0
HEARTATTACK             0
CORONARYHEARTDISEASE    0
STROKE                  0
ASTHMA                  0
SKINCANCER              0
OTHERCANCER             0
CHRONICBRONCHITIS       0
ARTHRITIS               0
DEPRESSIVEDISORDER      0
KIDNEYDISEASE           0
DIABETES                0
SLEEPTIME_GROUP         0
SEX_GROUP               0
WEIGHT_KILOGRAM         0
HEIGHT_METER            0
BMI_GROUP               0
RACE_GROUP              0
AGE_GROUP               0
dtype: int64

In [27]:
# Test 2: Check the dimensionality reduction
df_clean.shape

(389955, 19)

In [28]:
# Test 3: Visualize Cleaned Dataframe
df_clean.head(10)

,EXERCISE,HEARTATTACK,CORONARYHEARTDISEASE,STROKE,ASTHMA,SKINCANCER,OTHERCANCER,CHRONICBRONCHITIS,ARTHRITIS,DEPRESSIVEDISORDER,KIDNEYDISEASE,DIABETES,SLEEPTIME_GROUP,SEX_GROUP,WEIGHT_KILOGRAM,HEIGHT_METER,BMI_GROUP,RACE_GROUP,AGE_GROUP
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,3.0,NormalSleep,Female,58.967,1.626,UnderWeight,White,Elderly
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,LessSleep,Female,90.718,1.651,UnderWeight,Black,YoungAdult
2,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,NormalSleep,Female,64.410,1.473,UnderWeight,White,Elderly
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,LessSleep,Male,86.182,1.778,UnderWeight,White,Elderly
5,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,LessSleep,Female,78.018,1.575,UnderWeight,White,Elderly
6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,NormalSleep,Female,68.039,1.651,UnderWeight,White,Elderly
7,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,NormalSleep,Female,58.967,1.651,UnderWeight,White,Adult
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,LessSleep,Male,92.986,1.854,UnderWeight,White,OldAdult
9,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,3.0,NormalSleep,Female,68.492,1.600,UnderWeight,Black,Adult
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,OverSleep,Male,90.265,1.829,UnderWeight,White,Elderly

#### Export Data

In [29]:
df_clean.to_csv('DiabetesCleaned_2018.csv')

#### End.